---
title: TSS Shifting
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TSS Shifting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Prepare Data

```{r message=FALSE}
library("TSRexploreR")
library("ggplot2")

data(TSSs)

annotation <- system.file("extdata", "S288C_Annotation.gtf", package = "TSRexploreR")
assembly <- system.file("extdata", "S288C_Assembly.fasta", package = "TSRexploreR")
samples <- data.frame(
  sample_name=c(sprintf("S288C_D_%s", seq_len(3)), sprintf("S288C_WT_%s", seq_len(3))),
  file_1=rep(NA, 6), file_2=rep(NA, 6),
  condition=c(rep("Diamide", 3), rep("Untreated", 3))
)
```

```{r message=FALSE, warning=FALSE}
exp <- TSSs %>%
  tsr_explorer(
    genome_annotation=annotation, genome_assembly=assembly,
    sample_sheet=samples
  ) %>%
  format_counts(data_type = "tss") %>%
  tss_clustering(threshold=3) %>%  
  merge_samples(data_type = "tss", merge_group="condition") %>%
  merge_samples(data_type = "tsr", merge_group="condition")
```

## Calculate Shifting

Calculate the shifting scores.

```{r message=FALSE, warning=FALSE}
exp <- tss_shift(
  exp,
  sample_1=c(TSS="Untreated", TSR="Untreated"),
  sample_2=c(TSS="Diamide", TSR="Diamide"),
  comparison_name="Untreated_vs_Diamide",
  max_distance = 100, min_threshold = 10, n_resamples = 1000L
)
```

## Shifting Plots

Create a shift score rank plot.

```{r message=FALSE}
plot_shift_rank(exp) +
  scale_fill_viridis_c()
```

Create a shifting status count plot.

```{r message=FALSE}
plot_shift_count(exp) +
  scale_fill_viridis_d()
```

## Annotate Shifting

Annotate the shifted ranges.

```{r message=FALSE}
exp <- annotate_features(exp, data_type="shift", feature_type="transcript")
```

Plot the genomic distribution.

```{r message=FALSE}
plot_genomic_distribution(exp, data_type="shift") +
  scale_fill_viridis_d()
```

## Gene Tracks

Gene track of an example result.

```{r message=FALSE}
gene_tracks(
  exp, feature_name="YEL039C",
  samples=c(
    TSS="Untreated", TSR="Untreated",
    TSS="Diamide", TSR="Diamide"
  ),
  tss_colors=viridis::viridis(2),
  tsr_colors=viridis::viridis(2)
)
```
