
#' TSS Heatmap Count Matrix
#'
#' Generate count matrix to make TSS heatmap
#'
#' @include tsrexplorer.R
#' @include annotate.R
#'
#' @import tibble
#' @importFrom dplyr select filter group_by pull mutate_if rename
#' @importFrom magrittr %>%
#' @importFrom tidyr spread gather complete
#' @importFrom forcats fct_reorder
#' 
#' @param experiment tsrexplorer object with annotated TSSs
#' @param samples Either 'all' or name of samples to analyze
#' @param upstream Bases upstream to consider
#' @param downstream bases downstream to consider
#' @param threshold Reads required per TSS
#' @param anno_type Whether the heatmap is built on genes or transcripts ("geneId", "transcriptId")
#'
#' @return matrix of counts for each gene/transcript and position
#'
#' @export
#' @rdname tss_heatmap_matrix-function

tss_heatmap_matrix <- function(
	experiment,
	samples = "all",
	upstream = 1000,
	downstream = 1000,
	threshold = 1,
	anno_type = c("transcriptId", "geneId")
) {
	## Grab requested samples.
	if (samples == "all") samples <- names(experiment@experiment$TSSs)
	
	## Start preparing data for plotting.
	annotated_tss <- experiment@annotated$TSSs[samples] %>%
		bind_rows(.id = "sample") %>%
		rename(feature = anno_type) %>%
		filter(
			score >= threshold,
			between(distanceToTSS, -upstream, downstream)
		) %>%
		select(sample, feature, distanceToTSS, score) %>%
		mutate(feature = factor(feature))

	## Get order of genes for heatmap (mean accross samples).
	feature_order <- annotated_tss %>%
		mutate(feature = factor(feature)) %>%
		group_by(feature) %>%
		summarize(total_sum = sum(score)) %>%
		mutate(feature = fct_reorder(feature, desc(total_sum))) %>%
		pull(feature) %>%
		levels

	## Generate count matrix
	tss_matrix <- annotated_tss %>%
		complete(
			sample,
			feature = feature_order,
			distanceToTSS = -upstream:downstream,
			fill = list(score = 0)
		) %>%
		mutate(
			log2_score = log2(score + 1),
			feature = factor(feature, levels = feature_order)
		)

	return(tss_matrix)
}

#' Plot TSS Heatmap
#'
#' Plot TSS heatmap from count matrix generated by tss_count_matrix
#'
#' @import tibble
#' @import ggplot2
#' @importFrom dplyr transmute arrange pull mutate case_when desc
#' @importFrom tidyr gather
#' @importFrom forcats fct_rev
#' @importFrom magrittr %>%
#'
#' @param tss_count_matrix TSS count matrix from tss_count_matrix
#' @param max_value Max log2 value to truncate heatmap color
#' @param ncol Number of columns when plotting multiple samples
#'
#' @return ggplot2 object of TSS heatmap
#'
#' @export
#' @rdname plot_tss_heatmap-function

plot_tss_heatmap <- function(tss_heatmap_matrix, max_value = 5, ncol = 1) {
	
	## Set values above max_value to max_value.
	tss_heatmap_matrix <- tss_heatmap_matrix %>%
		mutate(
			log2_score = case_when(
				log2_score <= max_value ~ log2_score,
				log2_score > max_value ~ max_value
			)
		)

	## Generate TSS heatmap.
	p <- ggplot(tss_heatmap_matrix, aes(x = distanceToTSS, y = fct_rev(feature), fill = log2_score, color = log2_score)) +
		geom_tile() +
		theme_minimal() +
		theme(
			axis.text.y = element_blank(),
			panel.grid = element_blank()
		) +
		scale_fill_viridis_c(
			limits = c(0, max_value),
			breaks = c(0:max_value),
			labels = c(0:(max_value - 1), paste0(">", max_value)),
			name = "Log2(Score + 1)"
		) +
		scale_color_viridis_c(
			limits = c(0, max_value),
			breaks = c(0:max_value),
			labels = c(0:(max_value - 1), paste0(">", max_value)),
			name = "Log2(Score + 1)"
		) +
		labs(
			fill = "log2(Score + 1)",
			x = "Position",
			y = "Feature"
		) +
		facet_wrap(~ sample, ncol = ncol)

	return(p)
}

#' TSR Heatmap Count Matrix
#'
#' Generate count matrix to make TSR heatmap
#'
#' @include tsrexplorer.R
#' @include annotate.R
#'
#' @import tibble
#' @importFrom dplyr select mutate case_when bind_rows filter between group_by ungroup summarize
#' @importFrom magrittr %>%
#' @importFrom tidyr spread complete
#' @importFrom purrr pmap
#' 
#' @param experiment tsrexplorer object with annotated TSRs
#' @param sample Name of sample to analyze
#' @param upstream Bases upstream to consider
#' @param downstream bases downstream to consider
#' @param feature_type Whether the heatmap is built on genes or transcripts ("geneId", "transcriptId")
#'
#' @return matrix of counts for each gene/transcript and position
#'
#' @export
#' @rdname tsr_heatmap_matrix-function

tsr_heatmap_matrix <- function(
	experiment, sample,
	upstream = 1000, downstream = 1000,
	feature_type = c("transcriptId", "geneId")
) {
	## Prepare data to be made into count matrix
	annotated_tsr <- experiment@annotated$TSR[[sample]] %>%
		select(
			strand, start, end, geneId, transcriptId,
			geneStart, geneEnd, nTAGs
		) %>%
		mutate(
			startDist = case_when(
				strand == "+" ~ start - geneStart,
				strand == "-" ~ -(end - geneEnd)
			),
			endDist = case_when(
				strand == "+" ~ end - geneStart,
				strand == "-" ~ -(start - geneEnd)
			)
		) %>%
		select(startDist, endDist, nTAGs, geneId, transcriptId)

	if (feature_type == "transcriptId") {
		annotated_tsr <- annotated_tsr %>%
			pmap(function(startDist, endDist, nTAGs, transcriptId, geneId) {
				tibble(
					position = seq(startDist, endDist, 1),
					score = nTAGs,
					feature = transcriptId
				)
			}) %>%
			bind_rows
	} else {
		annotated_tsr <- annotated_tsr %>%
			pmap(function(startDist, endDist, nTAGs, transcriptId, geneId) {
				tibble(
					position = seq(startDist, endDist, 1),
					score = nTAGs,
					feature = geneId
				)
			}) %>%
			bind_rows()
	}

	annotated_tsr <- annotated_tsr %>%
		filter(between(position, -upstream, downstream)) %>%
		complete(feature, position = -upstream:downstream, fill = list(score = 0)) %>%
		group_by(feature, position) %>%
		summarize(score = sum(score)) %>%
		ungroup %>%
		mutate(log2_score = log2(score + 1)) %>%
		select(-score) %>%
		spread(key = position, value = log2_score)

	return(annotated_tsr)
}

#' Plot TSR Heatmap
#'
#' Plot TSR heatmap from count matrix generated by tsr_count_matrix
#'
#' @import tibble
#' @import ggplot2
#' @importFrom dplyr transmute arrange pull mutate case_when desc
#' @importFrom tidyr gather
#' @importFrom forcats fct_rev
#' @importFrom magrittr %>%
#'
#' @param tsr_count_matrix TSS count matrix from tss_count_matrix
#' @param max_value Max log2 value to truncate heatmap color
#'
#' @return ggplot2 object of TSS heatmap
#'
#' @export
#' @rdname plot_tsr_heatmap-function

plot_tsr_heatmap <- function(tsr_count_matrix, max_value = 8) {
	## order features by sum of TSR counts
	feature_order <- tsr_count_matrix %>%
		transmute(feature = feature, rowsums=rowSums(select(., 2:ncol(.)))) %>% 
		arrange(desc(rowsums)) %>%
		pull(feature)

	tsr_count_matrix <- mutate(tsr_count_matrix, feature = factor(feature, levels = feature_order))

	## Prepare data for plotting
	tsr_count_matrix <- tsr_count_matrix %>%
		gather(key="position", value="log2_score", -feature) %>%
		mutate(
			position = as.integer(position),
			log2_score = case_when(
				log2_score <= max_value ~ log2_score,
				log2_score > max_value ~ max_value
			)
		)
	
	## Plot TSR heatmap
	p <- ggplot(tsr_count_matrix, aes(x = position, y = fct_rev(feature), fill = log2_score, color = log2_score)) +
		geom_tile() +
		theme_minimal() +
		theme(
			axis.text.y = element_blank(),
			panel.grid = element_blank()
		) +
		scale_fill_viridis_c(
			limits = c(0, max_value),
			breaks = c(0:max_value),
			labels = c(0:(max_value - 1), paste0(">", max_value)),
			name = "Log2(Score + 1)"
		) +
		scale_color_viridis_c(
			limits = c(0, max_value),
			breaks = c(0:max_value),
			labels = c(0:(max_value - 1), paste0(">", max_value)),
			name = "Log2(Score + 1)"
		) +
		geom_vline(xintercept=0, lty=2, color="white") +
		labs(
			fill = "log2(Score + 1)",
			x = "Position",
			y = "Feature"
		)

	return(p)
}
