# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ShiftScoreFast <- function(x, y, k, xn, yn, w) {
    .Call(`_TSRexploreR_ShiftScoreFast`, x, y, k, xn, yn, w)
}

ShiftScore <- function(x, y, calcP, nresamp) {
    .Call(`_TSRexploreR_ShiftScore`, x, y, calcP, nresamp)
}

allTheShiftScores <- function(fhash, dists, scores, sample, calcP, nresamp, ntests) {
    .Call(`_TSRexploreR_allTheShiftScores`, fhash, dists, scores, sample, calcP, nresamp, ntests)
}

